name: Setup Environment

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo VITE_apiKey=${{ secrets.VITE_apiKey }} >> .env
          echo VITE_authDomain=${{ secrets.VITE_authDomain }} >> .env
          echo VITE_projectId=${{ secrets.VITE_projectId }} >> .env
          echo VITE_storageBucket=${{ secrets.VITE_storageBucket }} >> .env
          echo VITE_messagingSenderId=${{ secrets.VITE_messagingSenderId }} >> .env
          echo VITE_appId=${{ secrets.VITE_appId }} >> .env

      - name: Upload .env to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: env-file
          path: .env
